### ISSUE TITLE
The  most common keywords should appear in one or more of the meta-tag-for SEO

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#124]
## Description
The  most common keywords should appear in one or more of the meta-tags above. The  primary keywords should appear in the meta-tags to help identify the topic of the  webpage to search engines.

systers
projects 
code 
corps 
source 

Fix:
First of all, you must make sure that the page is using the meta-description tags.
Second, you must adjust these tags content in order to include some of the primary keywords displayed above.
## Acceptance Criteria
you must adjust these tags content in order to include some of the primary keywords displayed above

### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] gsoc/2009.html
- [ ]  gsoc/2010.html
- [ ]  gsoc/2011.html
- [ ]  gsoc/2012.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sara-02** [comment]
@AnkitKhatri55555 Is this related to https://github.com/systers/systers.github.io/issues/95? 
Can you update the previous issue instead of opening a new one?

**Comment by AnkitKhatri55555** [comment]
@sara-02 ,I think it should be kept as a separate one

**Comment by isunitha98selvan** [comment]
I would like to work on this.

**Comment by Saichethan** [comment]
@sara-02, @isunitha98selvam I think this is duplicate of #100 PR
Please check!

**Comment by BaaniLeen** [comment]
@Geekcoder555 Are you currently working on this issue? If not, @divyanshu-rawat Can I work on this issue since PR #100 has already been closed?

**Comment by divyanshu-rawat** [comment]
@Geekcoder555 are u still working on this? else I am assigning @BaaniLeen 👍

**Comment by divyanshu-rawat** [comment]
@BaaniLeen would like to work on it?

**Comment by BaaniLeen** [comment]
@ancyp @divyanshu-rawat I would like to work it. I feel this can be done throughout the GSoC period or at the end of it, when all our webpages are ready. What are you views upon it?

**Comment by BaaniLeen** [comment]
@pprathameshmore Would you like to work on this issue for the current gsoc18-code codebase?

**Comment by Geekcoder555** [comment]
Is anyone working on this?

**Comment by BaaniLeen** [comment]
@Geekcoder555 No. Can you please update the description wrt the gsoc18-code branch? And then request the @systers/maintainers-gh-pages to assign you the issue if you want to work on it. :)

**Comment by BaaniLeen** [comment]
@ancyp Since there is no acknowledgement from @Geekcoder555 , shall we unassign the issue and mark it as available for others?

**Comment by Geekcoder555** [comment]
Hey..I am now working on it..was a just busy with an internship.

**Comment by sarnava1** [comment]
@BaaniLeen I am claiming this. Please assign me this issue.
