### ISSUE TITLE
Create and Link the MongoDB Database on MLab with the Angular App - Epic

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#216]
## Description
As a contributor,
I need to create and Link the MongoDB database with Angular App,
so that I can use the API end points to serve data to and from the app.

### Update [Required]
- [ ] Will be mentioned in the sub-issues.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 hours (Will be updated as I add the sub-issues)
