### ISSUE TITLE
Create and Link MongoDB database on MLab with Angular App

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#218]
## Description
As a contributor,
I need to create and Link the MongoDB database with Angular App,
so that I can use the API end points to serve data to and from the app.

### Update [Required]
- [ ] Will be mentioned in the sub-issues.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
