### ISSUE TITLE
UI Update/CleanUp for GSoC18

### ISSUE THREAD

**Issue by ExactlyMay** [systers/systers.github.io#266]
## Description
As a developer,
I need to complete the branding of the app,
so that I can push a final product to production.

## Mocks
![0001](https://user-images.githubusercontent.com/2440938/43679434-3db49e54-97f3-11e8-801c-f2bc8de93abc.jpg)
-
![0006](https://user-images.githubusercontent.com/2440938/43679439-3df0a67e-97f3-11e8-990a-9935f5124e7a.jpg)
-
![0003](https://user-images.githubusercontent.com/2440938/43679436-3dca8c82-97f3-11e8-87ff-d168a79f06af.jpg)
-

### Update [Required]
- [ ] Navbar updated to ---
- [ ] Footer updated to ---
- [ ] Headers updated to ---
- [ ] Sub-headers updated to ---
- [ ] Text updated to ---
- [ ] Buttons updated to ---

### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours
