### ISSUE TITLE
Error: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#57]
## Description
A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge along with value chrome=1.
As a user,
I have to add the value 'IE-edge' to the http-equiv attribute of meta element,
so that it smoothly runs on IE as well.

## Mocks
--Not Applicable-

### Update [Required]
- [ ] index.html
- [ ] newcomers.html
- [ ] member-levels.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] contactus.html
- [ ] code-of-conduct.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/2011.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes.

**Comment by shreyateeza** [comment]
@MeepyMay please label this issue as 'first-timers-only' and 'Difficulty: easy'.

**Comment by MeepyMay** [comment]
Please update this as an Agile User Story description + Acceptance Criteria.

**Comment by shreyateeza** [comment]
@MeepyMay you can reopen it. I have done the changes. :+1:

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by shreyateeza** [comment]
@sara-02 @divyanshu-rawat @ancyp I think this issue is now approved by May as she has added a label to it. So can I work on this issue now?
P.S.: I already created a PR for this issue but it got closed later because it didn't follow the Systers Open Source Workflow.

**Comment by divyanshu-rawat** [comment]
@shreyateeza I have already assigned you 2 issues.
It would be great if you first send PR for those 2 (#58 #59) then you can continue to work on this as well because I think simultaneously dealing with all of them will be difficult.
let me know once you are done with sending PR for those 2.
@sara-02 correct me if I am my perception is wrong on this 👍

**Comment by anumehaagrawal** [comment]
@shreyateeza Are you done with the previous issues and do you want this issue to be assigned to you ? If not , we will open this issue to others :)

**Comment by divyanshu-rawat** [comment]
@anumehaagrawal As far as I know this is already open to being assigned to anyone @shreyateeza correct me If I am wrong?

**Comment by Supreme-Kai** [comment]
Hi :) Is this still open? If so I can work on it.

**Comment by bethanyr** [comment]
closing this issue since it applied to the old systers.io site.
