### ISSUE TITLE
No meta description tag found

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#95]
## Description
No meta description tag found. Use a description tag that accurately describes the contents of a web page. 
 A well-written meta description attracts more clicks in search results than an irrelevant or missing description.

## Acceptance Criteria
meta description tag should be added to html files.
### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] gsoc/2009.html
- [ ]  gsoc/2010.html
- [ ]  gsoc/2011.html
- [ ]  gsoc/2012.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-20 min

**Comment by shreyateeza** [comment]
@AnkitKhatri55555 Please create a checklist of all the files that require this addition in Update [Required] of Acceptance Criteria section.

**Comment by AnkitKhatri55555** [comment]
@shreyateeza , done!

**Comment by Saichethan** [comment]
Can I work on this...@Ankitkhatri

**Comment by AnkitKhatri55555** [comment]
@Saichethan , have you submitted a PR regarding this issue?

**Comment by BaaniLeen** [comment]
@Geekcoder555 Would you like to on this issue? Or is this free to be assigned anyone else? 
Please update! :)
